<!-- Generated by documentation.js. Update this documentation by updating the source code. -->

### Table of Contents

-   [externalFunctions][1]
-   [How to use it][2]
    -   [generateReqNo][3]
    -   [getApiKey][4]
    -   [generateqr][5]
        -   [Parameters][6]
    -   [listenForServiceProviderResponse][7]
        -   [Parameters][8]
    -   [listenForUserData][9]
        -   [Parameters][10]

## externalFunctions

## How to use it

Ask myearth.id to register yourself as Vendor. Once Registered you will get apiKey.

Now put this apiKey in api.js file

Place api.js file  inside src folder.

Call generateReqNo and getApiKey to store it somwhere persistently for the whole session.

Call listenForServiceProviderResponse to listen the socket emit for service provider name. Pass requestno as argument

Call listenForUserData  for getting user Data once the user has authorized the request.Pass requestno as argument.

Call generateqr for getting QR code data to be scanned by mobile.

### generateReqNo

Generates socket Id Called once and store it persistently somewhere

Returns **any** socketId for communication

### getApiKey

Returns API Key for vendor

### generateqr

API for generating QR Code

#### Parameters

-   `requestNo` **[string][11]** Socket Id for listening.

### listenForServiceProviderResponse

Start Listening for service provider name

#### Parameters

-   `requestNo`  
-   `cb`  

### listenForUserData

Socket listening for user Data after approval from user through app

#### Parameters

-   `requestNo` **any** 
-   `cb` **any** 

[1]: #externalfunctions

[2]: #how-to-use-it

[3]: #generatereqno

[4]: #getapikey

[5]: #generateqr

[6]: #parameters

[7]: #listenforserviceproviderresponse

[8]: #parameters-1

[9]: #listenforuserdata

[10]: #parameters-2

[11]: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String
